#!/usr/bin/env python

"""
Print the contents of the version [version] of the file [filename] on the screen.
Author: Jacob Zaidi
"""

import os
import sys

def main(filename, version):
    f = open(".versiondir/" + filename + "." + str(version), "r")
    print f.read(),
    f.close()


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
