#!/usr/bin/env python

"""
Permanently removes all versions except the current version of file [filename].
Author: Jacob Zaidi
"""

import os
import sys

def main(filename):
    for i in range(2, 7):
	if os.path.exists(".versiondir/" + filename + "." + str(i)):
		os.remove(".versiondir/" + filename + "." + str(i))

if __name__ == '__main__':
    main(sys.argv[1])
