#!/bin/bash
# Jacob Zaidi
# rmversions $1
# Permanently removes all versions except the current version of file $1

if [ "$1" != "" ]; then
    for i in {2..6}; do
        rm -f .versiondir/$1.$i
    done    
fi
